version: '3'
services:
    nginx:
        image: nginx:latest
        # 端口映射
        ports:
            - "80:80"
        # 依赖关系 先跑php
        depends_on:
            - "php"
        # 数据卷
        volumes:
            # 映射主机./conf.d目录到容器/etc/nginx/conf.d目录
            - $PWD/conf.d/:/etc/nginx/conf.d/
            #- $PWD/html/:/usr/share/nginx/html/
            - $PWD/html/:/var/www/html/
            - $PWD/logs/nginx/:/usr/local/nginx/logs/
        networks:
            - app_net
        # 容器名称
        container_name: "compose-nginx"
    php:
        build: ./php-mysqli
        # image指定build Dockerfile生成镜像的名称
        image: php:7.2-fpm-mysqli
        ports:
            - "9000:9000"
        volumes:
            - "$PWD/html:/var/www/html"
            - "$PWD/conf.d/ubuntu/sources.list:/etc/apt/sources.list"
        networks:
            - app_net
        container_name: "compose-php"
        networks:
            app_net:
                # 固定子网ip，网段必须在子网络10.10.*.*
                ipv4_address: 10.10.10.4
    mysql:
        image: mysql:5.7
        ports:
            - "53306:3306"
        # 环境变量
        environment:
            # mysql密码
            - MYSQL_ROOT_PASSWORD=565859
        networks:
            app_net:
                # 固定子网ip，网段必须在子网络10.10.*.*
                ipv4_address: 10.10.10.1
        container_name: "compose-mysql"
        volumes:
            - $PWD/data/mysql:/var/lib/mysql/
            - $PWD/conf.d/mysql/:/etc/mysql/conf.d/
            - $PWD/logs/mysql/:/var/logs/mysql/
    redis:
        image: redis:4
        ports: 
            - "6379:6379"
        volumes:
            - "$PWD/data/redis:/data/"
            - "$PWD/conf/redis.conf:/etc/redis/redis.conf"
        networks:
            app_net:
                # 固定子网ip，网段必须在子网络10.10.*.*
                ipv4_address: 10.10.10.2
        container_name: "compose-redis"
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        hostname: phpmyadmin
        restart: always
        ports:
            - 58080:80
        depends_on:
            - "mysql"
        volumes:
            - $PWD/sessions:/sessions
            - $PWD/conf.d/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
            - $PWD/conf.d/ubuntu/sources.list:/etc/apt/sources.list
        environment:
            #- PMA_ARBITRARY:1
            - PMA_HOST:10.10.10.1
            #- PMA_PORT:3306
            #- "PMA_USER=root"
            #- "PMA_PASSWORD=565859"
        networks:
            app_net:
                # 固定子网ip，网段必须在子网络10.10.*.*
                ipv4_address: 10.10.10.3
    svn:
        build: ./subversion
        image: ubuntu
        container_name: "compose-svn"
        networks:
            - app_net
        ports:
            - "3690:3690"
        volumes:
           - $PWD/subversion/src_store:/opt/svn/src_store
           - $PWD/html:/var/www/html   
networks:
    # 配置docker network
    app_net:
        driver: bridge
        ipam:
            config:
                # 子网络
                - subnet: 10.10.0.0/16

