---
# Default Kibana configuration from kibana-docker.
#
server.name: kibana
server.host: "0.0.0.0"
elasticsearch.url: http://elasticsearch:9200
# #xpack.monitoring.ui.container.elasticsearch.enabled: false
server.port: 5601
# #xpack.security.enabled: false